blog/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.PostList.as_view(), name='home'),
    path('<slug:slug>/', views.post_detail, name='post_detail'),
    path('<slug:slug>/edit_comment/<int:comment_id>',
         views.comment_edit, name='comment_edit'),
    path('<slug:slug>/delete_comment/<int:comment_id>',
         views.comment_delete, name='comment_delete'),
    path('traveller/<str:username>/', views.traveller_profile, name='traveller_profile'),
    path('traveller/<str:username>/edit/', views.edit_traveller_profile, name='edit_traveller_profile'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("about/", include("about.urls"), name="about-urls"),
    path("accounts/", include("allauth.urls")),
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include("blog.urls"), name="blog-urls"),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

STATUS = ((0, "Draft"), (1, "Published"))

CATEGORY_COUNTRIES = [
    ('afghanistan', 'Afghanistan'),
    ('albania', 'Albania'),
    ('algeria', 'Algeria'),
    ('andorra', 'Andorra'),
    ('angola', 'Angola'),
    ('antigua_deps', 'Antigua & Deps'),
    ('argentina', 'Argentina'),
    ('armenia', 'Armenia'),
    ('australia', 'Australia'),
    ('austria', 'Austria'),
    ('azerbaijan', 'Azerbaijan'),
    ('bahamas', 'Bahamas'),
    ('bahrain', 'Bahrain'),
    ('bangladesh', 'Bangladesh'),
    ('barbados', 'Barbados'),
    ('belarus', 'Belarus'),
    ('belgium', 'Belgium'),
    ('belize', 'Belize'),
    ('benin', 'Benin'),
    ('bhutan', 'Bhutan'),
    ('bolivia', 'Bolivia'),
    ('bosnia_herzegovina', 'Bosnia Herzegovina'),
    ('botswana', 'Botswana'),
    ('brazil', 'Brazil'),
    ('brunei', 'Brunei'),
    ('bulgaria', 'Bulgaria'),
    ('burkina', 'Burkina'),
    ('burundi', 'Burundi'),
    ('cambodia', 'Cambodia'),
    ('cameroon', 'Cameroon'),
    ('canada', 'Canada'),
    ('cape_verde', 'Cape Verde'),
    ('central_african_rep', 'Central African Rep'),
    ('chad', 'Chad'),
    ('chile', 'Chile'),
    ('china', 'China'),
    ('colombia', 'Colombia'),
    ('comoros', 'Comoros'),
    ('congo', 'Congo'),
    ('congo_democratic_rep', 'Congo {Democratic Rep}'),
    ('costa_rica', 'Costa Rica'),
    ('croatia', 'Croatia'),
    ('cuba', 'Cuba'),
    ('cyprus', 'Cyprus'),
    ('czech_republic', 'Czech Republic'),
    ('denmark', 'Denmark'),
    ('djibouti', 'Djibouti'),
    ('dominica', 'Dominica'),
    ('dominican_republic', 'Dominican Republic'),
    ('east_timor', 'East Timor'),
    ('ecuador', 'Ecuador'),
    ('egypt', 'Egypt'),
    ('el_salvador', 'El Salvador'),
    ('equatorial_guinea', 'Equatorial Guinea'),
    ('eritrea', 'Eritrea'),
    ('estonia', 'Estonia'),
    ('ethiopia', 'Ethiopia'),
    ('fiji', 'Fiji'),
    ('finland', 'Finland'),
    ('france', 'France'),
    ('gabon', 'Gabon'),
    ('gambia', 'Gambia'),
    ('georgia', 'Georgia'),
    ('germany', 'Germany'),
    ('ghana', 'Ghana'),
    ('greece', 'Greece'),
    ('grenada', 'Grenada'),
    ('guatemala', 'Guatemala'),
    ('guinea', 'Guinea'),
    ('guinea_bissau', 'Guinea-Bissau'),
    ('guyana', 'Guyana'),
    ('haiti', 'Haiti'),
    ('honduras', 'Honduras'),
    ('hungary', 'Hungary'),
    ('iceland', 'Iceland'),
    ('india', 'India'),
    ('indonesia', 'Indonesia'),
    ('iran', 'Iran'),
    ('iraq', 'Iraq'),
    ('ireland_republic', 'Ireland {Republic}'),
    ('israel', 'Israel'),
    ('italy', 'Italy'),
    ('ivory_coast', 'Ivory Coast'),
    ('jamaica', 'Jamaica'),
    ('japan', 'Japan'),
    ('jordan', 'Jordan'),
    ('kazakhstan', 'Kazakhstan'),
    ('kenya', 'Kenya'),
    ('kiribati', 'Kiribati'),
    ('korea_north', 'Korea North'),
    ('korea_south', 'Korea South'),
    ('kosovo', 'Kosovo'),
    ('kuwait', 'Kuwait'),
    ('kyrgyzstan', 'Kyrgyzstan'),
    ('laos', 'Laos'),
    ('latvia', 'Latvia'),
    ('lebanon', 'Lebanon'),
    ('lesotho', 'Lesotho'),
    ('liberia', 'Liberia'),
    ('libya', 'Libya'),
    ('liechtenstein', 'Liechtenstein'),
    ('lithuania', 'Lithuania'),
    ('luxembourg', 'Luxembourg'),
    ('macedonia', 'Macedonia'),
    ('madagascar', 'Madagascar'),
    ('malawi', 'Malawi'),
    ('malaysia', 'Malaysia'),
    ('maldives', 'Maldives'),
    ('mali', 'Mali'),
    ('malta', 'Malta'),
    ('marshall_islands', 'Marshall Islands'),
    ('mauritania', 'Mauritania'),
    ('mauritius', 'Mauritius'),
    ('mexico', 'Mexico'),
    ('micronesia', 'Micronesia'),
    ('moldova', 'Moldova'),
    ('monaco', 'Monaco'),
    ('mongolia', 'Mongolia'),
    ('montenegro', 'Montenegro'),
    ('morocco', 'Morocco'),
    ('mozambique', 'Mozambique'),
    ('myanmar_burma', 'Myanmar, {Burma}'),
    ('namibia', 'Namibia'),
    ('nauru', 'Nauru'),
    ('nepal', 'Nepal'),
    ('netherlands', 'Netherlands'),
    ('new_zealand', 'New Zealand'),
    ('nicaragua', 'Nicaragua'),
    ('niger', 'Niger'),
    ('nigeria', 'Nigeria'),
    ('norway', 'Norway'),
    ('oman', 'Oman'),
    ('pakistan', 'Pakistan'),
    ('palau', 'Palau'),
    ('panama', 'Panama'),
    ('papua_new_guinea', 'Papua New Guinea'),
    ('paraguay', 'Paraguay'),
    ('peru', 'Peru'),
    ('philippines', 'Philippines'),
    ('poland', 'Poland'),
    ('portugal', 'Portugal'),
    ('qatar', 'Qatar'),
    ('romania', 'Romania'),
    ('russian_federation', 'Russian Federation'),
    ('rwanda', 'Rwanda'),
    ('st_kitts_nevis', 'St Kitts & Nevis'),
    ('st_lucia', 'St Lucia'),
    ('saint_vincent_grenadines', 'Saint Vincent & the Grenadines'),
    ('samoa', 'Samoa'),
    ('san_marino', 'San Marino'),
    ('sao_tome_principe', 'Sao Tome & Principe'),
    ('saudi_arabia', 'Saudi Arabia'),
    ('senegal', 'Senegal'),
    ('serbia', 'Serbia'),
    ('seychelles', 'Seychelles'),
    ('sierra_leone', 'Sierra Leone'),
    ('singapore', 'Singapore'),
    ('slovakia', 'Slovakia'),
    ('slovenia', 'Slovenia'),
    ('solomon_islands', 'Solomon Islands'),
    ('somalia', 'Somalia'),
    ('south_africa', 'South Africa'),
    ('south_sudan', 'South Sudan'),
    ('spain', 'Spain'),
    ('sri_lanka', 'Sri Lanka'),
    ('sudan', 'Sudan'),
    ('suriname', 'Suriname'),
    ('swaziland', 'Swaziland'),
    ('sweden', 'Sweden'),
    ('switzerland', 'Switzerland'),
    ('syria', 'Syria'),
    ('taiwan', 'Taiwan'),
    ('tajikistan', 'Tajikistan'),
    ('tanzania', 'Tanzania'),
    ('thailand', 'Thailand'),
    ('togo', 'Togo'),
    ('tonga', 'Tonga'),
    ('trinidad_tobago', 'Trinidad & Tobago'),
    ('tunisia', 'Tunisia'),
    ('turkey', 'Turkey'),
    ('turkmenistan', 'Turkmenistan'),
    ('tuvalu', 'Tuvalu'),
    ('uganda', 'Uganda'),
    ('ukraine', 'Ukraine'),
    ('united_arab_emirates', 'United Arab Emirates'),
    ('united_kingdom', 'United Kingdom'),
    ('united_states', 'United States'),
    ('uruguay', 'Uruguay'),
    ('uzbekistan', 'Uzbekistan'),
    ('vanuatu', 'Vanuatu'),
    ('vatican_city', 'Vatican City'),
    ('venezuela', 'Venezuela'),
    ('vietnam', 'Vietnam'),
    ('yemen', 'Yemen'),
    ('zambia', 'Zambia'),
    ('zimbabwe', 'Zimbabwe')
]


class Post(models.Model):
    """
    Stores a single blog post entry related to :model:`auth.User`.
    """

    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    country = models.CharField(max_length=50, choices=CATEGORY_COUNTRIES, blank=False, null=False, default='other')
    featured_image = CloudinaryField('image', default='placeholder')
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    excerpt = models.TextField(blank=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return f"{self.title} - {self.country}"

    def approved_comments_count(self):
        return self.comments.filter(approved=True).count()


class Comment(models.Model):
    """
    Stores a single comment entry related to :model:`auth.User`
    and :model:`blog.Post`.
    """
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='commenter')
    body = models.TextField()
    approved = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return f"Comment {self.body} by {self.author}"


class Traveller(models.Model):
    """
    Stores additional information about a traveller related to :model:`auth.User`.
    """

    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='traveller')
    bio = models.TextField(blank=True)
    profile_image = CloudinaryField('image', default='placeholder')
    fav_country = models.CharField(max_length=50, choices=CATEGORY_COUNTRIES, blank=False, default='other')
    wishlist_country = models.CharField(max_length=50, choices=CATEGORY_COUNTRIES, blank=False, default='other')

    def __str__(self):
        return f"{self.user.username}'s Profile"

blog/forms.py
from .models import Comment, Traveller
from django import forms
from django_summernote.widgets import SummernoteWidget
from cloudinary.forms import CloudinaryFileField


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Traveller
        fields = ['bio', 'profile_image', 'fav_country', 'wishlist_country']
        widgets = {
            'bio': SummernoteWidget(),
            'profile_image': CloudinaryFileField().widget,
        }
        labels = {
            'bio': 'Biography (A few words about yourself)',
            'profile_image': 'Profile Picture',
            'fav_country': 'Favourite Country',
            'wishlist_country': 'Country you want to visit the most',
        }

blog/views.py
from django.shortcuts import render, get_object_or_404, reverse, redirect
from django.views import generic
from django.contrib import messages
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from .models import Post, Comment, Traveller
from .forms import CommentForm, ProfileForm

# Create your views here.


class PostList(generic.ListView):
    queryset = Post.objects.filter(status=1)
    template_name = "blog/index.html"
    paginate_by = 8


def post_detail(request, slug):
    """
    Display an individual :model:`blog.Post`.

    **Context**

    ``post``
        An instance of :model:`blog.Post`.

    **Template:**

    :template:`blog/post_detail.html`
    """

    queryset = Post.objects.filter(status=1)
    post = get_object_or_404(queryset, slug=slug)
    comments = post.comments.all().order_by("-created_on")
    comment_count = post.comments.filter(approved=True).count()
    if request.method == "POST":
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()
            messages.add_message(
                request, messages.SUCCESS,
                'Comment submitted and awaiting approval'
            )

    comment_form = CommentForm()

    return render(
        request,
        "blog/post_detail.html",
        {
            "post": post,
            "comments": comments,
            "comment_count": comment_count,
            "comment_form": comment_form,
        },
    )


def comment_edit(request, slug, comment_id):
    """
    view to edit comments
    """
    if request.method == "POST":

        queryset = Post.objects.filter(status=1)
        post = get_object_or_404(queryset, slug=slug)
        comment = get_object_or_404(Comment, pk=comment_id)
        comment_form = CommentForm(data=request.POST, instance=comment)

        if comment_form.is_valid() and comment.author == request.user:
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.approved = False
            comment.save()
            messages.add_message(request, messages.SUCCESS, 'Comment Updated!')
        else:
            messages.add_message(request, messages.ERROR, 'Error updating comment!')

    return HttpResponseRedirect(reverse('post_detail', args=[slug]))


def comment_delete(request, slug, comment_id):
    """
    view to delete comment
    """
    queryset = Post.objects.filter(status=1)
    post = get_object_or_404(queryset, slug=slug)
    comment = get_object_or_404(Comment, pk=comment_id)

    if comment.author == request.user:
        comment.delete()
        messages.add_message(request, messages.SUCCESS, 'Comment deleted!')
    else:
        messages.add_message(request, messages.ERROR, 'You can only delete your own comments!')

    return HttpResponseRedirect(reverse('post_detail', args=[slug]))


def traveller_profile(request, username):
    """
    view to display traveller profile page
    """
    user = get_object_or_404(User, username=username)
    traveller, created = Traveller.objects.get_or_create(user=user)

    return render(
        request,
        "blog/traveller_profile.html",
        {
            "traveller": traveller,
            "user": user,
        },
    )


@login_required
def edit_traveller_profile(request, username):
    """
    view to edit traveller profile
    """
    user = get_object_or_404(User, username=username)
    traveller, created = Traveller.objects.get_or_create(user=user)

    if request.user != traveller.user:
        messages.error(
            request,
            "You do not have permission to edit this profile"
        )
        return redirect("traveller_profile", username=username)

    if request.method == "POST":
        form = ProfileForm(request.POST, request.FILES, instance=traveller)
        if form.is_valid():
            form.save()
            messages.success(request, "Your profile has been updated successfully")
            return redirect("traveller_profile", username=username)
        else:
            messages.error(request, "Error updating profile")
    else:
        form = ProfileForm(instance=traveller)

    return render(
        request,
        "blog/profile_form.html",
        {
            "form": form,
            "traveller": traveller
        }
    )

blog/templates/blog/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container-fluid">
    <div class="row">

        <!-- Blog Entries Column -->
        <div class="col-12 mt-3 left">
            <div class="row">
                {% for post in post_list %}
                <div class="col-md-3">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="image-container">
                                {% if "placeholder" in post.featured_image.url %}
                                <img class="card-img-top" src="{% static 'images/default.jpg' %}"
                                alt="placeholder image">
                                {% else %}
                                <img class="card-img-top" src=" {{ post.featured_image.url }}" alt="{{ post.title }}">
                                {% endif %}
                                <div class="image-flash">
                                    <p class="country">Country: {{ post.get_country_display }}</p>
                                </div>
                            </div>
                            <a href="{% url 'post_detail' post.slug %}" class="post-link">
                                <h2 class="card-title mt-3">{{ post.title }}</h2>
                                <p class="card-text"> {{ post.excerpt }}</p>
                            </a>

                            <hr />
                            <p class="card-text h6">{{ post.created_on}}</p>
                            <p class="card-text h6"><i class="far fa-comments"></i> {{ post.approved_comments_count }}</p>                            
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:8 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            
            <!-- Previous Button -->
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo; Previous</a>
            </li>
            {% endif %}
            
            <!-- Page Numbers -->
            {% for page_num in page_obj.paginator.page_range %}
                {% if page_num == page_obj.number %}
                <li class="page-item active">
                    <span class="page-link">{{ page_num }}</span>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                </li>
                {% endif %}
            {% endfor %}
            
            <!-- Next Button -->
            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next &raquo;</a>
            </li>
            {% endif %}
            
        </ul>
    </nav>
    {% endif %}
</div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %} {% block content %}
{% load static %}
{% load crispy_forms_tags %}

<div class="post-title">
    <h1 class="text-center">{{ post.title }}</h1>
    <p class="text-center">By {{ post.author|title }} | {{ post.created_on }}</p>
    <p class="text-center">Country: {{ post.get_country_display }}</p>
    {% if post.featured_image %}
    <div class="text-center">
        {% if "placeholder" in post.featured_image.url %}
        <img src="{% static 'images/default.jpg' %}" class="img-fluid"
            alt="placeholder image">
        {% else %}
        <img src="{{ post.featured_image.url }}" class="img-fluid"
            alt="{{ post.title }}">
        {% endif %}
    </div>
    {% endif %}
</div>

<div class="container">
    <div class="row">
        <div class="col card mb-4  mt-3 left  top">
            <div class="card-body">                
                <div class="card-text">
                    {{ post.content | safe }}
                </div>
            </div>
        </div>
    </div>
  <!-- Displaying count of comments -->
  <div class="row">
    <div class="col-12">
      <strong class="text-secondary">
        <i class="far fa-comments"></i> {{ post.approved_comments_count }}
      </strong>
    </div>
    <div class="col-12">
      <hr>
    </div>
  </div>
  <!-- Displaying Comments -->
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 ">
      <h3>Comments:</h3>
      <div class="card-body">    
        {% if comments.count == 0 %}   
        <p>No comments have been made on this post yet.</p>
        {% endif %}
        {% for comment in comments %}
        <div class="p-2 comments
            {% if not comment.approved and comment.author == user %}
            faded{% elif not comment.approved %} d-none{% endif %}">
            <p class="font-weight-bold">
                {{ comment.author|title }} wrote on
            <span class="font-weight-normal">
              {{ comment.created_on }}:
            </span>
            </p>
            <div id="comment{{ comment.id }}">
            {{ comment.body | linebreaks }}
            </div>
            {% if not comment.approved and comment.author == user %}
            <p class="approval">
            This comment is awaiting approval
            </p>
          {% endif %}
          {% if user.is_authenticated and comment.author == user %}
            <button class="btn btn-delete"
            comment_id="{{ comment.id }}">Delete</button>
            <button class="btn btn-edit"
            comment_id="{{ comment.id }}">Edit</button>
          {% endif %}
        </div>
        {% endfor %}
      </div>
    </div>
    <!-- Creating New Comments -->
    <div class="col-md-4 card mb-4 mt-3">
      <div class="card-body">
        {% if user.is_authenticated %}
        <h3>Leave a comment:</h3>
        <p>Posting as: {{ user.username }}</p>
        <form id="commentForm" method="post"
          style="margin-top: 1.3em;">
          {{ comment_form | crispy }}
          {% csrf_token %}
          <button id="submitButton" type="submit"
            class="btn btn-signup">Submit</button>
        </form>
        {% else %}
        <p><a href="{% url 'account_login' %}">Log in</a> to leave a comment</p>
        {% endif %}
      </div>
    </div>
  </div>
</div>

<!-- Delete confirmation modal -->
<div class="modal fade" id="deleteModal" tabindex="-1"
  aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"
          id="deleteModalLabel">Delete comment?</h5>
        <button type="button" class="btn-close"
          data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete your comment?
        This action cannot be undone.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary"
          data-bs-dismiss="modal">Close</button>
        <a id="deleteConfirm" href="#" class="btn
          btn-danger">Delete</a>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

{% block extras %}
<script src="{% static 'js/comments.js' %}"></script>
{% endblock %}

blog/templates/blog/profile_form.html
{% extends "base.html" %}


{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-8">
            <h2>Edit your profile</h2>
            <p>Feel free to add a profile picture, tell us a bit about yourself and let us know your favourite country and which country is top of your list to visit.</p>            
            <div class="profile-form mt-4 mb-4">
                
                <form method="post" enctype="multipart/form-data">{% csrf_token %}
                    {{ form }}
                    <input type="submit" value="Update Profile">
                </form>
                          
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/traveller_profile.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<!-- page to view traveller's profile photo, name, bio, favourite country and country that is top of their wishlist to visit -->

<div class="container mt-5">
    <h2>{{ user.username|title }}'s Profile</h2>
    <div class="row">   
      {% if "placeholder" in traveller.profile_image.url %}
      <img src="{% static 'images/placeholder.jpg' %}" style="width: 25%;"
        alt="placeholder image" >
      {% else %}
      <img src="{{ traveller.profile_image.url }}" style="width: 75%;"
        alt="{{ traveller.user.username }}">
      {% endif %}
        <div class="col-md-8 mb-4 mt-3">
            <h2>About {{ user.username|title }}</h2>
            <div>{{ traveller.bio|safe }}</div>
            <h4>What's your favourite country that you have visited?</h4>
            <p>{{ traveller.fav_country|title }}</p>
            <h4>Which country is top of your wishlist to visit?</h4>
            <p>{{ traveller.wishlist_country|title }}</p>           
                        
            {% if request.user == traveller.user %}
            <a role="button" class="btn btn-signup" href="{% url 'edit_traveller_profile' username=traveller.user.username %}">Edit Profile</a>
            {% endif %}            
        </div>
    </div>
</div>

{% endblock %}